steps:
  - name: node:14.17.3
    entrypoint: yarn
    args: ["install", "--check-files"]
  - name: node:14.17.3
    entrypoint: yarn
    args: ["clean"]
  - name: node:14.17.3
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "gs://ws-paperframed-store"]